### PR TITLE
Clean up CFBundleDocumentTypes

### PR DESCRIPTION
**Pull request by tssm**
Apple has the concept of Uniform Type Identifiers[1] which allows to associate an app to a bunch of file-types at once. This commit add the `public.text` TUI to the Info.plist file and removes unneeded declarations. I didn't test all of them, but they can be added as needed

[1]: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis

### CODE REVIEW

**Comment by yatli** [comment]
In summary:

Add:
```
      <dict>
          <key>LSItemContentTypes</key>
          <array>
              <string>public.text</string>
          </array>
          <key>CFBundleTypeRole</key>
          <string>Editor</string>
      </dict>
```

Remove:

a few file extensions.


@tssm is that correct?

**Comment by tssm** [comment]
Exactly. A lot of file extensions are already covered by `public.text`, like Markdown and popular programming languages, like the C family, Python, Ruby, etc.

**Comment by yatli** [comment]
Did you test if the file association works?
Last time I played around it, it wasn't working -- cannot remember the details, perhaps one of the following:

- No option to open a file with FVim
- Opens FVim, but doesn't open the file

**Comment by tssm** [comment]
Yes, that's why I didn't remove all of them, for example `.hs` files are not part of `public.text` (yet?), but `.md` files work, `.py` files work, `.mm` work... I din't test all of them tough.

When I say they work it means that when you right-click a file and select `Open with` FVim appears in the list of associated applications

**Comment by yatli** [comment]
Thanks for your clarification. I think this is good for merge now.

> Opens FVim, but doesn't open the file

Maybe next time :)

**Comment by tssm** [comment]
Thanks to you for FVim! I'll keep on eye on this in case it doesn't work for other users

**Pull request merged**
